config/routes.rb
require_relative '../app/api/v1/api'
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  mount Sidekiq::Web => '/sidekiq'

  root 'books#index'
  resources :books do
    resources :reviews, only: [ :create, :update, :destroy, :edit ]
  end
  resources :rankings, only: [ :index ]
  mount ::V1::API => '/api'

  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 12 }

  has_many :reviews, dependent: :destroy

  def self.books_key
    'books/index'
  end

  def book_reviews_key
    "book/#{id}/reviews"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!
  after_action :clear_cache, only: %i[create update destroy]
  EXPIRY_DURATION = 10.minutes.freeze

  def index
    page = params[:page].to_i.positive? ? params[:page] : 1
    per_page = params[:per_page].to_i.positive? ? params[:per_page] : 3
    cache_key = Book.books_key

    @books = Rails.cache.fetch(cache_key, expires_in: EXPIRY_DURATION) do
      Book.order(:name).all.to_a
    end

    @books = Kaminari.paginate_array(@books).page(page).per(per_page)
  end

  def show
    cache_key = @book.book_reviews_key
    @reviews = Rails.cache.fetch(cache_key, expires_in: EXPIRY_DURATION) do
      @book.reviews.to_a
    end
    @review = Review.new

    service = BookViewService.new(@book)
    service.increment_view
    @views_today = service.get_view_count
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      redirect_to new_book_path(error: @book.errors.full_messages)
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      redirect_to edit_book_path(error: @book.errors.full_messages)
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def clear_cache
    Rails.cache.delete_matched('books/page/*/per_page/*')
  end

  def set_book
    @book ||= Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:name, :description, :release)
  end
end

app/views/books/_book.html.erb
<div>
  <%= link_to book.name, book_path(book) %>
</div>

app/views/books/_form.html.erb
<% if params[:error] %>
  <div>
    <ul>
      <% params[:error].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= link_to "Back Home", root_path %>

<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :release %>
    <%= form.date_select :release %>
  </div>

  <%= form.submit %>
<% end %>

app/views/books/edit.html.erb
Edit Page

<div>
<%= render "form",book: @book, error: params[:error] %>
</div>

app/views/books/index.html.erb
<h1>Books</h1>

<%=link_to "Book Ranking" ,rankings_path%>
<div>
  <%= button_to "Log out", destroy_user_session_path(current_user), method: :delete %>
</div>

<%= current_user.email %>

<h1>Articles</h1>
<ul>
  <% if current_user %>
    <li>
      Logged in: You have the ability to create and manage books.
    </li>
  <% else %>
    <li>
      Not Logged in: You have limited access to create and manage books.
    </li>
  <% end %>
</ul>

<div>
  <%= link_to "Create book", new_book_path %>
</div>

<div>
  <%= render @books %>
</div>

<div>
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
Create New Book

<div>
<%= render "form",book: @book, error: params[:error] %>
</div>

app/views/books/show.html.erb
<%= link_to "Back to home", root_path %>

<div>
  <% if current_user %>
    LOGGED IN: You have the ability to create and manage comments.
  <% else %>
    NOT LOGGED IN: You have limited access to create and manage comments.
  <% end %>

  <div>
    <h1><%= @book.name %></h1>
    <div>
      <%= link_to "Edit", edit_book_path(@book) %>
      <%= button_to "Delete", @book, method: :delete %>
    </div>
    <p><%= @book.description %></p>
    <p>Published on: <%= @book.release %></p>
    <p>Views Today: <%= @views_today %></p>
  </div>

  <h2>Reviews</h2>

  <% @book.reviews.each do |review| %>
    <div>
      <p><%= review.comment %></p>
      <p>Given <%= review.star %> stars</p>
      <%= link_to "Edit comment", edit_book_review_path(@book, review) %>
      <%= button_to "Delete Comment", book_review_path(@book, review), method: :delete %>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>

  <% if params[:error] %>
    <div>
      <ul>
        <% params[:error].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <h1>Add Reviews Here</h1>
    <%= form_with model: [@book, @book.reviews.build] do |form| %>
      <p>
        <%= form.label :comment %><br>
        <%= form.text_area :comment %>
      </p>
      <p>
        <%= form.label :star %><br>
        <%= form.number_field :star %>
      </p>
      <p>
        <%= form.submit "Submit Review" %>
      </p>
    <% end %>
  </div>
</div>